### ISSUE TITLE
npm start throws error

### ISSUE THREAD

**Issue by bakkiraju** [G07cha/pomodoro#31]
{ Error: ENOENT: no such file or directory, open '/Users/bilahari/Library/Application Support/pomodoro/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at getConfig (/Users/bilahari/pomodoro/index.js:124:28)
    at Object.<anonymous> (/Users/bilahari/pomodoro/index.js:32:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
  errno: -2,

**Comment by G07cha** [comment]
Hi @bakkiraju, thanks for reporting but this actually doesn't affect the application because it happened inside of `try-catch` block and usually happens if the user wasn't changing any settings yet. The application should be visible in menubar, please let me know if it didn't happen.
